### ISSUE TITLE
TypeError: fsevents is not a constructor

### ISSUE THREAD

**Issue by rneild** [rajivjc/clinicaltrials-on-blockchain#1]
Environment: AWS EC2 node v6.11.0. Default install on clean hardware. First time user. Looks like this is not your code but the truffle build?

`truffle serve -p 8081
Serving static assets in ./build on port 8081...
Rebuilding...
/home/ec2-user/.nvm/versions/node/v6.11.0/lib/node_modules/truffle/build/cli.bundled.js:123830
  return (new fsevents(path)).on('fsevent', callback).start();
          ^

TypeError: fsevents is not a constructor
    at createFSEventsInstance (/home/ec2-user/.nvm/versions/node/v6.11.0/lib/node_modules/truffle/build/cli.bundled.js:123830:11)
    at setFSEventsListener (/home/ec2-user/.nvm/versions/node/v6.11.0/lib/node_modules/truffle/build/cli.bundled.js:123884:16)
    at FSWatcher.FsEventsHandler._watchWithFsEvents (/home/ec2-user/.nvm/versions/node/v6.11.0/lib/node_modules/truffle/build/cli.bundled.js:124048:16)
    at FSWatcher.<anonymous> (/home/ec2-user/.nvm/versions/node/v6.11.0/lib/node_modules/truffle/build/cli.bundled.js:124182:25)
    at LOOP (fs.js:1773:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
`

**Comment by rajivjc** [comment]
Can you try using truffle 3.2.1 ? This seem to be an issue with the latest truffle version 3.3.0

npm install -g truffle@3.2.1
